log:
  filename: 'log.log'
  logger_level: 'DEBUG'
  console_level: 'DEBUG'
  file_level: 'INFO'

excel:
  filename: 'web_cases.xlsx'

tester:
  mobile_phone: '18584086762'
  pwd: 'yey1201abc'

investor:
  mobile_phone: '13981970269'
  pwd: '12345678'

administrator:
  mobile_phone: '13982204699'
  pwd: '12345678'

host: 'http://120.78.128.25:8765'

strftime_format:
  '%Y-%m-%d-%H-%M-%S'